# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

#When adding new keywords to categories also add them in the Keywords table!
Category.create(name:'Announcement', keywords:'announcement,discurs,anunt,stiri,news,stire')
Category.create(name:'Audition', keywords:'audition,auditie,talent,xfactor')
Category.create(name:'Party', keywords:'party,petrecere,dans,dance,alcohol,alcool,drinks,music,muzica,karaoke')
Category.create(name:'Seminar', keywords:'seminar')
Category.create(name:'Ceremony', keywords:'ceremony,ceremonie')
Category.create(name:'Concert', keywords:'concert,music,muzica,rock,pop,r&b,rap')
Category.create(name:'Conference', keywords:'conference,conferinta,university,universitate,facultate,ted,tedx,speeker,speech,discurs')
Category.create(name:'Exam', keywords:'exam,examen,evaluare')
Category.create(name:'Exhibition', keywords:'exhibition,expozitie,muzeu,museum,art,arta')
Category.create(name:'Festival', keywords:'festival')
Category.create(name:'Forum', keywords:'forum')
Category.create(name:'Lecture', keywords:'lecture')
Category.create(name:'Fundraising', keywords:'fundraising')
Category.create(name:'Meeting', keywords:'meeting,intalnire')
Category.create(name:'Reading', keywords:'reading')
Category.create(name:'Movie', keywords:'movie,film,cinematograf,cinama,filmul')
Category.create(name:'Recreation', keywords:'recreation, parc,park,recreere,natura,nature,lake,lac')
Category.create(name:'Protest', keywords:'protest,ponta')
Category.create(name:'Sport', keywords:'sport,alergare,fotbal,football,tenis,tennis,bicicleta,ciclism,cycling,bicycle')
Category.create(name:'Training', keywords:'training,traininguri')
Category.create(name:'Competition', keywords:'competition,competitie,concurs,premiu,prize,premii,prizes')
Category.create(name:'Regional Activity', keywords:'')
Category.create(name:'Campus Activity', keywords:'')

Keywords.create(keyword:'announcement', score:1, parent:'')
Keywords.create(keyword:'anunt', score:0, parent:'announcement')
Keywords.create(keyword:'news', score:1, parent:'')
Keywords.create(keyword:'stiri', score:0, parent:'news')
Keywords.create(keyword:'stire', score:0, parent:'news')
Keywords.create(keyword:'audition', score:1, parent:'')
Keywords.create(keyword:'auditie', score:0, parent:'audition')
Keywords.create(keyword:'talent', score:1, parent:'')
Keywords.create(keyword:'xfactor', score:1, parent:'')
Keywords.create(keyword:'party', score:1, parent:'')
Keywords.create(keyword:'petrecere', score:0, parent:'party')
Keywords.create(keyword:'dance', score:1, parent:'')
Keywords.create(keyword:'dans', score:0, parent:'dance')
Keywords.create(keyword:'alcohol', score:1, parent:'alcool')
Keywords.create(keyword:'alcool', score:0, parent:'alcohol')
Keywords.create(keyword:'drinks', score:1, parent:'')
Keywords.create(keyword:'music', score:1, parent:'')
Keywords.create(keyword:'muzica', score:0, parent:'music')
Keywords.create(keyword:'karaoke', score:1, parent:'')
Keywords.create(keyword:'seminar', score:1, parent:'')
Keywords.create(keyword:'ceremony', score:1, parent:'')
Keywords.create(keyword:'ceremonie', score:0, parent:'ceremony')
Keywords.create(keyword:'concert', score:1, parent:'')
Keywords.create(keyword:'rock', score:1, parent:'')
Keywords.create(keyword:'pop', score:1, parent:'')
Keywords.create(keyword:'rap', score:1, parent:'')
Keywords.create(keyword:'r&b', score:1, parent:'')
Keywords.create(keyword:'conference', score:1, parent:'')
Keywords.create(keyword:'conferinta', score:0, parent:'conference')
Keywords.create(keyword:'speech', score:1, parent:'')
Keywords.create(keyword:'discurs', score:0, parent:'speech')
Keywords.create(keyword:'speeker', score:0, parent:'speech')
Keywords.create(keyword:'ted', score:1, parent:'')
Keywords.create(keyword:'tedx', score:0, parent:'ted')
Keywords.create(keyword:'university', score:1, parent:'')
Keywords.create(keyword:'universitate', score:0, parent:'university')
Keywords.create(keyword:'facultate', score:0, parent:'university')
Keywords.create(keyword:'exam', score:1, parent:'')
Keywords.create(keyword:'examen', score:0, parent:'exam')
Keywords.create(keyword:'evaluare', score:0, parent:'exam')
Keywords.create(keyword:'exhibition', score:1, parent:'')
Keywords.create(keyword:'expozitie', score:0, parent:'exhibition')
Keywords.create(keyword:'museum', score:1, parent:'')
Keywords.create(keyword:'muzeu', score:0, parent:'museum')
Keywords.create(keyword:'art', score:1, parent:'')
Keywords.create(keyword:'arta', score:0, parent:'art')
Keywords.create(keyword:'festival', score:1, parent:'')
Keywords.create(keyword:'forum', score:1, parent:'')
Keywords.create(keyword:'lecture', score:1, parent:'')
Keywords.create(keyword:'fundraising', score:1, parent:'')
Keywords.create(keyword:'meeting', score:1, parent:'')
Keywords.create(keyword:'intalnire', score:0, parent:'meeting')
Keywords.create(keyword:'reading', score:1, parent:'')
Keywords.create(keyword:'movie', score:1, parent:'announcement')
Keywords.create(keyword:'film', score:0, parent:'movie')
Keywords.create(keyword:'cinematograf', score:0, parent:'movie')
Keywords.create(keyword:'cinema', score:0, parent:'movie')
Keywords.create(keyword:'filmul', score:0, parent:'movie')
Keywords.create(keyword:'recreation', score:1, parent:'')
Keywords.create(keyword:'recreere', score:0, parent:'recreation')
Keywords.create(keyword:'park', score:1, parent:'')
Keywords.create(keyword:'parc', score:0, parent:'parc')
Keywords.create(keyword:'nature', score:1, parent:'')
Keywords.create(keyword:'natura', score:0, parent:'nature')
Keywords.create(keyword:'lake', score:1, parent:'')
Keywords.create(keyword:'lac', score:0, parent:'lake')
Keywords.create(keyword:'protest', score:1, parent:'')
Keywords.create(keyword:'ponta', score:0, parent:'protest')
Keywords.create(keyword:'sport', score:1, parent:'')
Keywords.create(keyword:'alergare', score:1, parent:'')
Keywords.create(keyword:'forbal', score:0, parent:'football')
Keywords.create(keyword:'football', score:1, parent:'')
Keywords.create(keyword:'cycling', score:1, parent:'')
Keywords.create(keyword:'ciclism', score:0, parent:'cycling')
Keywords.create(keyword:'bicicleta', score:0, parent:'cycling')
Keywords.create(keyword:'bicycle', score:0, parent:'cycling')
Keywords.create(keyword:'tennis', score:1, parent:'')
Keywords.create(keyword:'tenis', score:0, parent:'tennis')
Keywords.create(keyword:'training', score:1, parent:'')
Keywords.create(keyword:'traininguri', score:0, parent:'training')
Keywords.create(keyword:'competition', score:1, parent:'')
Keywords.create(keyword:'competitie', score:0, parent:'competition')
Keywords.create(keyword:'concurs', score:1, prent:'competition')
Keywords.create(keyword:'prize', score:0, parent:'')
Keywords.create(keyword:'prizes', score:0, parent:'prize')
Keywords.create(keyword:'premiu', score:0, parent:'prize')
Keywords.create(keyword:'premii', score:0, parent:'prize')


