# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Category.create(name:'Announcement', keywords:'announcement,discurs,anunt,stiri')
Category.create(name:'Audition', keywords:'audition,auditie,talent,xfactor,')
Category.create(name:'Party', keywords:'party,petrecere,dans,alcool,drinks,music,muzica,karaoke')
Category.create(name:'Seminar', keywords:'seminar')
Category.create(name:'Ceremony', keywords:'ceremony,ceremonie')
Category.create(name:'Concert', keywords:'concert,music,muzica,rock,pop,r&b,rap,hip-hop')
Category.create(name:'Conference', keywords:'conference,conferinta,university,facultate,ted,tedx,speeker,speech,discurs')
Category.create(name:'Exam', keywords:'exam,examen,evaluare')
Category.create(name:'Exhibition', keywords:'exhibition,expozitie,muzeu,museum,art,arta')
Category.create(name:'Festival', keywords:'festival')
Category.create(name:'Forum', keywords:'forum')
Category.create(name:'Lecture', keywords:'lecture')
Category.create(name:'Fundraising', keywords:'fundraising')
Category.create(name:'Meeting', keywords:'meeting,intalnire')
Category.create(name:'Reading', keywords:'reading')
Category.create(name:'Movie', keywords:'movie,film,cinematograf,cinama,filmul')
Category.create(name:'Recreation', keywords:'recreation, parc,park,recreation,natura,nature,lake,lac')
Category.create(name:'Protest', keywords:'protest,ponta')
Category.create(name:'Sport', keywords:'sport,alergare,fotbal,football,tenis,tennis,bicicleta,ciclism,cycling,bicycle')
Category.create(name:'Training', keywords:'training,traininguri')
Category.create(name:'Competition', keywords:'competition,competitie,concurs,premiu,prize,premii,prizes')
Category.create(name:'Regional Activity', keywords:'')
Category.create(name:'Campus Activity', keywords:'')
